apiVersion: v1
appVersion: latest
description: A Helm chart for infra-server
name: infra-server
version: 0.2.10
home: https://github.com/stackrox/infra
sources:
  - https://github.com/stackrox/infra
annotations:
  acsDemoVersion: 4.9.0
  automationFlavorsVersion: 0.12.7
  ocpCredentialsMode: Passthrough
dependencies:
  - name: argo-workflows
    version: "0.45.9"
    repository: "https://argoproj.github.io/argo-helm"
  - name: kube-prometheus
    version: 11.3.10
    repository: https://charts.bitnami.com/bitnami
