apiVersion: v1
appVersion: latest
description: A Helm chart for infra-server
name: infra-server
version: 0.2.10
home: https://github.com/stackrox/infra
sources:
  - https://github.com/stackrox/infra
annotations:
  acsDemoVersion: 4.5.4
  automationFlavorsVersion: 0.12.6-2-g772f067746-snapshot
  ocpCredentialsMode: Passthrough
