name: UI tests

on: [push]

jobs:
  create-cluster-with-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create KinD Cluster
        id: kind
        uses: helm/kind-action@v1
        with:
          registry: true
          registry_name: local-registry
          registry_port: 5001
          registry_enable_delete: true

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
          buildkitd-config-inline: |
            [registry."${{ steps.kind.outputs.LOCAL_REGISTRY }}"]
              http = true
              insecure = true
          driver-opts: network=host

      - name: Tag
        run: |
          LOCAL_DOCKER_REPO="${{ steps.kind.outputs.LOCAL_REGISTRY }}/${{ github.repository }}"
          echo "LOCAL_DOCKER_REPO=${LOCAL_DOCKER_REPO}" >> $GITHUB_ENV
          echo "LOCAL_DOCKER_TAG=${LOCAL_DOCKER_REPO}:${{ steps.version.outputs.docker_version }}" >> $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.LOCAL_DOCKER_TAG }}

      - name: Test
        run: |
          set -x
          set +e
          kubectl config current-context
          docker run --rm ${{ env.LOCAL_DOCKER_TAG }}
          make test-e2e
