name: UI tests

on: [push]

jobs:
  create-cluster-with-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create KinD Cluster
        uses: helm/kind-action@v1

      - name: tags
        run: |
          echo "TAG=$(make tag)" | tee -a $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: image/Dockerfile
          push: false
          load: true
          tags: quay.io/rhacs-eng/infra-server:${{ env.TAG }}

      - name: Load image into KinD
        run: |
          kind load docker-image quay.io/rhacs-eng/infra-server:${{ env.TAG }}

      - name: Deploy
        run: |
          set -x
          set +e
          kubectl config current-context
          make deploy-local
          kubectl wait --for=condition=ready pod -l app=infra-server -n infra --timeout=5m || true
          kubectl describe deploy/infra-server -n infra || true
          kubectl get pods -n infra || true
          kubectl port-forward -n infra svc/infra-server-service 8443:8443 >/dev/null 2>&1 &
          echo "PF_PID=$!" | tee -a $GITHUB_ENV

      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run test:e2e

      - name: cleanup
        if: always()
        run: |
          set -x
          echo "Killing port-forward process ${PF_PID}"
          kill "$PF_PID" || true
