name: UI tests

on: [push]

jobs:
  create-cluster-with-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create KinD Cluster
        id: kind
        uses: helm/kind-action@v1
        with:
          registry: true
          registry_name: local-registry
          registry_port: 5001
          registry_enable_delete: true

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
          buildkitd-config-inline: |
            [registry."${{ steps.kind.outputs.LOCAL_REGISTRY }}"]
              http = true
              insecure = true
          driver-opts: network=host

      - name: tags
        run: |
          echo "TAG=$(make tag)" | tee -a $GITHUB_ENV
          echo "REGISTRY=${{ steps.kind.outputs.LOCAL_REGISTRY }}" | tee -a $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: image/Dockerfile
          push: true
          tags: ${{ steps.kind.outputs.LOCAL_REGISTRY }}/${{ env.TAG }}

      - name: Deploy
        run: |
          set -x
          set +e
          kubectl config current-context
          make deploy-local
          kubectl wait --for=condition=ready pod -l app=infra-server -n infra --timeout=5m || true
          kubectl describe deploy/infra-server -n infra || true
          kubectl get pods -n infra || true
          kubectl port-forward -n infra svc/infra-server-service 8443:8443 >/dev/null 2>&1 &
          echo "PF_PID=$!" | tee -a $GITHUB_ENV

      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run test:e2e

      - name: cleanup
        if: always()
        run: |
          set -x
          echo "Killing port-forward process ${PF_PID}"
          kill "$PF_PID" || true
